### ISSUE TITLE
Conflict with plugin MaxBlogPress Ping Optimizer

### ISSUE THREAD

**Issue by seyfro** [dcramer/wp-lifestream#19]
I have the current version of the Plugin MB Ping Optimizer (http://www.maxblogpress.com/plugins/mpo/) installed together with WP Lifestream. I noticed that my webspace was filling up and I didnt know why. I then found out by chance, that the table wp_mbp_ping_optimizer was morre than a Gigabyte in size. I dont know what exactly caused this, but as I run the plugin MB Ping Optimizer on other blogs without wp-lifestream, I assume, that there must be a connection to your plugin.
I assume that everytime wp-lifestream checks for new entries, all sites which shouldnt be pinged are entered into the table. As this happens every few minutes, I assume that the table is getting big soon. 
My solution was to disable the plugin MB Ping Optimizer.

**Comment by tonyduckles** [comment]
As of a few releases ago, wp-lifestream is using the new custom-post-type functionality in Wordpress to create actual "posts" (i.e. rows in wp_posts) for each lifestream entry. After a brief look at the MBPO code, it looks like that plugin is hooking some of the Wordpress post-create/edit/save events and verbosely logging messages about what it's doing for each post. Hence, if your Lifestream is active, this will incur a lot of traffic in your MBPO logs.

If you want to use MBPO along with Lifestream, I'm guessing that you'll want to hack the code some to short-circuit and ignore certain post-types, e.g. wp-lifestream's "lsevent" post-type. That should greatly reduce the number of MBPO logged messages (i.e. entries in the wp_mbp_ping_optimizer table).

IMO, this is a deficiency with the MBPO plugin rather than Lifestream. Wordpress sites can have all kinds of custom post-types and MBPO just isn't correctly being aware of them.
